from typing import Protocol


class TenantProvisioningRepositoryPort(Protocol):
    async def provision(
        self,
        *,
        tenant_id: str | None,
        name: str,
        site_id: str,
        site_name: str,
        admin_user_id: str,
        admin_email: str,
    ) -> str:
        """Creates `tenants`, the default `sites` row, the admin `users` row, and its
        `user_credentials` row (`auth_subject=NULL`) atomically. Returns the
        resolved tenant id: when `tenant_id` is `None`, it is generated by the
        database (`gen_random_uuid()` default); otherwise the supplied value.

        Raises `TenantAlreadyExistsError` if a supplied `tenant_id` already exists.
        """
        ...
