from typing import Literal, Protocol

from app.modules.identity.domain.authn_result import AuthnResult


class AuthPort(Protocol):
    async def verify_password(self, email: str, password: str) -> AuthnResult: ...

    async def verify_federated(self, provider: Literal["google"], id_token: str) -> AuthnResult: ...

    async def start_password_reset(self, email: str, redirect_to: str) -> None: ...

    async def invite_user(self, email: str, redirect_to: str) -> AuthnResult: ...

    async def complete_password_reset(self, recovery_token: str, new_password: str) -> AuthnResult: ...
